version: "3.8"

services:
  frontend-web:
    build:
      context: ./Frontend-Web
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - primary-server
    networks:
      - app-network

  primary-server:
    build:
      context: ./Socket-Server
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
